name: Publish to Clojars

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Leiningen
      run: |
        wget -O /tmp/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x /tmp/lein
        sudo mv /tmp/lein /usr/local/bin/lein
        lein version

    - name: Cache Leiningen dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.lein
        key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-

    - name: Run tests
      run: lein test

    - name: Generate and check POM
      run: |
        lein pom
        cat pom.xml

    - name: Deploy to Clojars
      env:
        clojars_username: ${{ secrets.CLOJARS_USERNAME }}
        clojars_password: ${{ secrets.CLOJARS_PASSWORD }}
      run: |
        echo "Environment variables set:"
        echo "clojars_username: $clojars_username"
        echo "clojars_password length: ${#clojars_password}"
        echo ""
        echo "Starting deployment..."
        lein deploy clojars
        echo "Deployment completed successfully!"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes
          See [CHANGELOG.md](CHANGELOG.md) for details.

          ## Installation
          ```clojure
          [hector/pickdict "${{ github.ref_name }}"]
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
