name: Publish to Clojars

# Temporarily disabled - use manual deployment
# on:
#   push:
#     tags:
#       - 'v*.*.*'

# Manual trigger only
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check secrets
      run: |
        echo "CLOJARS_USERNAME exists: ${{ secrets.CLOJARS_USERNAME != '' }}"
        echo "CLOJARS_PASSWORD exists: ${{ secrets.CLOJARS_PASSWORD != '' }}"

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Leiningen
      run: |
        wget -O /tmp/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x /tmp/lein
        sudo mv /tmp/lein /usr/local/bin/lein

    - name: Run tests
      run: lein test

    - name: Deploy to Clojars
      run: lein deploy clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
