name: Publish to Clojars

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Leiningen
      run: |
        wget -O /tmp/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x /tmp/lein
        sudo mv /tmp/lein /usr/local/bin/lein

    - name: Run tests
      run: lein test

    - name: Deploy to Clojars
      run: lein deploy clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
